### PR TITLE
Update IndexScrollSection.vue

### PR DESCRIPTION
**Pull request by dandrejczuk**
PKT is a blockchain enables anyone to become an ISP. Users allocate bandwidth from their local internet connections and build a global, decentralized edge network, by the people, for the people.
"Changed enables to enabling"

### CODE REVIEW

**Comment by cjdelisle** [comment]
Thanks! 🎉

**Comment by dandrejczuk** [comment]
Hi Caleb,
Was my edit not good or does it take a certain amount of time before it
gets entered on the site?  This was my first pull request so I'm just
curious of the process.

Thanks!

Regards,
Dwayne

**Comment by dandrejczuk** [comment]
Disregard my last..apparently I was looking at a cached copy.  Thanks!

**Comment by cjdelisle** [comment]
In the case of pkt.cash I have to deploy it, with docs.pkt.cash deployment is automatic.

Thanks,
Caleb

**Pull request merged**
